name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            mdsajid020/shifthandover:latest
            mdsajid020/shifthandover:${{ github.sha }}

      - name: Deploy to Azure Linux VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            docker pull mdsajid020/shifthandover:latest
            docker stop shifthandover_app || true
            docker rm shifthandover_app || true
            docker run -d \
              --name shifthandover_app \
              --network shift_handover_app_default \
              -e DATABASE_URL="mysql+pymysql://user:password@shift_handover_app_db_1:3306/shift_hadnover" \
              -p 80:5000 \
              mdsajid020/shifthandover:latest




